In [4]:
import pandas as pd
import joblib

hasil_lr  = joblib.load('../model/hasil_lr.pkl')
hasil_rf  = joblib.load('../model/hasil_rf.pkl')
hasil_gbt = joblib.load('../model/hasil_gbt.pkl')

daftar_model = [hasil_lr, hasil_rf, hasil_gbt]

rekap_testing = []
for h in daftar_model:
    m_tr = h['Training']
    m_te = h['Testing']
    rekap_testing.append({
        'Model': h['Model'],
        'RMSE (Training)': m_tr['Root mean squared error'],
        'RMSE (Testing)': m_te['Root mean squared error'],
        'MAE (Testing)': m_te['Mean absolute error'],
        'MSE (Testing)': m_te['Mean squared error'],
        'MAPE (Testing)': m_te['Mean absolute percentage error'],
        'R2 (Testing)': m_te['R2'],
        'Akurasi R2 (%)': round(m_te['R2'] * 100, 1),
        'Adjusted R2': m_te['Adjusted R2']
    })

df_rekap = pd.DataFrame(rekap_testing)
print("TABEL PERBANDINGAN AKHIR KETIGA MODEL: ")
display(df_rekap)

print("\nURUTAN MODEL TERBAIK BERDASARKAN RMSE TESTING TERKECIL:")
display(df_rekap.sort_values(by='RMSE (Testing)', ascending=True).reset_index(drop=True))

joblib.dump(df_rekap, 'df_rekap.pkl')
print("Data tabel perbandingan berhasil disimpan ke 'output/df_rekap.pkl'!")

TABEL PERBANDINGAN AKHIR KETIGA MODEL:

,Model,RMSE (Training),RMSE (Testing),MAE (Testing),MSE (Testing),MAPE (Testing),R2 (Testing),Akurasi R2 (%),Adjusted R2
0,Linear Regression,0.659,0.889,0.252,0.790,1.581,0.548,54.8,0.547
1,Random Forest Regression,0.451,0.850,0.159,0.723,1.218,0.587,58.7,0.585
2,Gradient Boosted Trees Regression,0.443,0.801,0.170,0.641,1.238,0.633,63.3,0.632

URUTAN MODEL TERBAIK BERDASARKAN RMSE TESTING TERKECIL:

,Model,RMSE (Training),RMSE (Testing),MAE (Testing),MSE (Testing),MAPE (Testing),R2 (Testing),Akurasi R2 (%),Adjusted R2
0,Gradient Boosted Trees Regression,0.443,0.801,0.170,0.641,1.238,0.633,63.3,0.632
1,Random Forest Regression,0.451,0.850,0.159,0.723,1.218,0.587,58.7,0.585
2,Linear Regression,0.659,0.889,0.252,0.790,1.581,0.548,54.8,0.547

Data tabel perbandingan berhasil disimpan ke 'output/df_rekap.pkl'!